name: Art
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: W Hudson Miller <email@example.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  path: ^1.4.1
  DollLibCorrect:
    git: git://github.com/FarragoFiction/DollLibCorrect.git

dev_dependencies:
  build_runner:  ^1.3.0
  build_test: ^0.10.2
  build_web_compilers: ^1.2.0


transformers:

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc

